name: Keep Render Alive
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (UTC time)
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render to prevent shutdown
        run: curl -X GET https://your-api.onrender.com/health
